/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Native */

#ifndef _Included_Native
#define _Included_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Native
 * Method:    instanceMethod
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_Native_instanceMethod
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     Native
 * Method:    classMethod
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_Native_classMethod
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
